name: Copy Files to Another Repo

on:
  workflow_dispatch: # Trigger manually or define other triggers (e.g., push or schedule)

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repository
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Set up the target repository
      - name: Clone Target Repository
        run: |
          git clone https://github.com/TeleporterDash/teleporterdash.github.io.git target-repo
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }} # Create and store this in secrets

      # Copy files to the target repository
      - name: Copy Files
        run: |
          cp -r Sound/LevelSoundtracks/* target-repo/Sound/LevelSoundtracks/ # Copy files

      # Commit and push changes to the target repository
      - name: Commit and Push Changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync files from source repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }} # Reuse the token for pushing
